name: Deploy To gh-pages manually
on:
  workflow_dispatch:
    inputs:
      angular-env:
        type: string
        required: true

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
      working-directory: ./
    - run: npm run ${{ github.event.inputs.angular-env }} --if-present
      working-directory: ./
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./dist/guests-dashboard-pwa
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}